version: '2'
services:
  mysqlblue:
    container_name: mysqlblue
    image: domibus/mysql:development
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "3304:3306"
  mysqlred:
    container_name: mysqlred
    image: domibus/mysql:development
    command: --lower-case-table-names=1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "3305:3306"
  domibusblue:
    container_name: domibusblue
    image: domibus/tomcat/blue:development
    environment:
      - dbServerName=mysqlblue
      - dbServerPort=3306
    command: dockerize -wait tcp://$dbServerName:$dbServerPort -timeout 20s
    ports:
      - "8080:8080"
    depends_on:
      - mysqlblue
  domibusred:
      container_name: domibusred
      image: domibus/tomcat/red:development
      environment:
        - dbServerName=mysqlred
        - dbServerPort=3306
      command: dockerize -wait tcp://$dbServerName:$dbServerPort -timeout 20s
      ports:
        - "9080:8080"
      depends_on:
        - mysqlred